name : Build and test
on:
    create:
    workflow_dispatch:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-and-test-cpu:
        strategy:
            matrix:
                os: [ubuntu-latest]
                python-version: [3.10]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Install OpenMP
              run: |
                sudo apt-get update
                sudo apt-get install libomp-dev -y
            
            - name: Install dependencies
              run: pip install -r requirements.txt
            
            - name: Init Weights
              run: python3 pythonscripts/model.py
            
            - name: Compile and run
              run: make run_cpu && ./executable
    
    build-cuda-fp32:
      strategy:
        matrix:
          os: [ubuntu-latest]
          python-version: [3.10]
      runs-on: ubuntu-latest
      container:
        image: nvidia/cuda:12.4.1-devel-ubuntu22.04
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Install Python and dependencies
          run: |
            apt-get update
            apt-get install -y python3 python3-pip
            python3 -m pip install -r requirements.txt
        
        - name: Init Weights
          run: python3 pythonscripts/model.py
    
        - name: Build FP32 checkpoint
          run: make run_cuda && ./executable