name: Build and test
on:
    create:
    workflow_dispatch:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-and-test-cpu:
        strategy:
            matrix:
                os: [ubuntu-latest]
                python-version: [3.10]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Install OpenMP
              run: |
                sudo apt-get update
                sudo apt-get install libomp-dev -y
            
            - name: Install dependencies
              run: pip install -r requirements.txt
            
            - name: Init Weights
              run: python3 pythonscripts/model.py
            
            - name: Test python
              run: python3 test.py
            
            - name: Compile and run
              run: make run_cpu 